# Generated by Django 5.2.7 on 2025-10-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('unvan', models.TextField(blank=True, verbose_name='Ünvan')),
                ('dogum_tarixi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarixi')),
                ('qeyd_tarixi', models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat Tarixi')),
                ('yenileme_tarixi', models.DateTimeField(auto_now=True, verbose_name='Yeniləmə Tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstifadəçi Profili',
                'verbose_name_plural': 'İstifadəçi Profilləri',
                'ordering': ['-qeyd_tarixi'],
            },
        ),
    ]
