# Generated by Django 5.2.7 on 2025-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Məlumat adı')),
                ('value', models.TextField(verbose_name='Dəyər')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon CSS class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Əlaqə Məlumatı',
                'verbose_name_plural': 'Əlaqə Məlumatları',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Mövzu')),
                ('test_type', models.CharField(blank=True, max_length=100, verbose_name='Test növü')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Üstünlük verilən tarix')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'Baxılır'), ('resolved', 'Həll edilib'), ('closed', 'Bağlanıb')], default='new', max_length=15, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin qeydləri')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Təcili')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Cavablandırılıb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Cavab tarixi')),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abunə olma tarixi')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abunəlikdən çıxma tarixi')),
            ],
            options={
                'verbose_name': 'Newsletter Abunəliyi',
                'verbose_name_plural': 'Newsletter Abunəlikləri',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], max_length=20, verbose_name='Platform')),
                ('username', models.CharField(max_length=100, verbose_name='İstifadəçi adı')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon CSS class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sosial Media',
                'verbose_name_plural': 'Sosial Media Hesabları',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
