# Generated by Django 5.2.7 on 2025-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şirkət adı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('mission', models.TextField(blank=True, verbose_name='Missiya')),
                ('vision', models.TextField(blank=True, verbose_name='Vizyon')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('working_hours', models.CharField(max_length=100, verbose_name='İş saatları')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='Logo')),
                ('established_year', models.IntegerField(blank=True, null=True, verbose_name='Təsis ili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Şirkət',
                'verbose_name_plural': 'Şirkət məlumatları',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Sual')),
                ('answer', models.TextField(verbose_name='Cavab')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ-lar',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xidmət adı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('icon', models.CharField(help_text='FontAwesome icon class məsələn: fas fa-microscope', max_length=50, verbose_name='Icon CSS class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('position', models.CharField(choices=[('doctor', 'Həkim'), ('lab_technician', 'Laborant'), ('manager', 'Menecer'), ('nurse', 'Tibb bacısı'), ('other', 'Digər')], max_length=20, verbose_name='Vəzifə')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Şəkil')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='Təcrübə (il)')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='İxtisas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Komanda üzvü',
                'verbose_name_plural': 'Komanda üzvləri',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
