# Generated by Django 5.2.7 on 2025-10-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('category_type', models.CharField(choices=[('blood', 'Qan Analizləri'), ('hormone', 'Hormon Testləri'), ('infection', 'İnfeksiya Testləri'), ('allergy', 'Allergodiaqnostika'), ('biochemistry', 'Biokimya'), ('immunology', 'İmmunologiya'), ('other', 'Digər')], max_length=15, unique=True, verbose_name='Kateqoriya tipi')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon CSS class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Kateqoriyası',
                'verbose_name_plural': 'Test Kateqoriyaları',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Test adı')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Test kodu')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('preparation_info', models.TextField(blank=True, help_text='Test öncəsi hazırlıq göstərişləri', verbose_name='Hazırlıq məlumatları')),
                ('sample_type', models.CharField(help_text='Qan, sidik, ağız suyu və s.', max_length=100, verbose_name='Nümunə növü')),
                ('result_time', models.CharField(help_text='Məsələn: 1-2 iş günü', max_length=50, verbose_name='Nəticə müddəti')),
                ('normal_range', models.TextField(blank=True, verbose_name='Normal dəyərlər')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (AZN)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Endirimli qiymət (AZN)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Məşhur test')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlər',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Paket adı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paket qiyməti (AZN)')),
                ('discount_percentage', models.IntegerField(help_text='Fərdi qiymətlərdən nə qədər endirim', verbose_name='Endirim faizi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne çıxarılmış')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tests', models.ManyToManyField(related_name='packages', to='tests.test', verbose_name='Testlər')),
            ],
            options={
                'verbose_name': 'Test Paketi',
                'verbose_name_plural': 'Test Paketləri',
                'ordering': ['order', 'name'],
            },
        ),
    ]
